/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.models.CheckCommon;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CheckWithReportIds
 */
public class CheckWithReportIdsTest {
    private final CheckWithReportIds model = new CheckWithReportIds();

    /**
     * Model tests for CheckWithReportIds
     */
    @Test
    public void testCheckWithReportIds() {
        // TODO: test CheckWithReportIds
    }

    /**
     * Test the property 'reports'
     */
    @Test
    public void reportsTest() {
        // TODO: test reports
    }

}
