/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Check
 */
public class CheckTest {
    private final Check model = new Check();

    /**
     * Model tests for Check
     */
    @Test
    public void testCheck() {
        // TODO: test Check
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'downloadUri'
     */
    @Test
    public void downloadUriTest() {
        // TODO: test downloadUri
    }

    /**
     * Test the property 'formUri'
     */
    @Test
    public void formUriTest() {
        // TODO: test formUri
    }

    /**
     * Test the property 'redirectUri'
     */
    @Test
    public void redirectUriTest() {
        // TODO: test redirectUri
    }

    /**
     * Test the property 'resultsUri'
     */
    @Test
    public void resultsUriTest() {
        // TODO: test resultsUri
    }

    /**
     * Test the property 'reportNames'
     */
    @Test
    public void reportNamesTest() {
        // TODO: test reportNames
    }

    /**
     * Test the property 'applicantId'
     */
    @Test
    public void applicantIdTest() {
        // TODO: test applicantId
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'applicantProvidesData'
     */
    @Test
    public void applicantProvidesDataTest() {
        // TODO: test applicantProvidesData
    }

    /**
     * Test the property 'suppressFormEmails'
     */
    @Test
    public void suppressFormEmailsTest() {
        // TODO: test suppressFormEmails
    }

    /**
     * Test the property 'asynchronous'
     */
    @Test
    public void asynchronousTest() {
        // TODO: test asynchronous
    }

    /**
     * Test the property 'reportIds'
     */
    @Test
    public void reportIdsTest() {
        // TODO: test reportIds
    }

}
