/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GenericAddress
 */
public class GenericAddressTest {
    private final GenericAddress model = new GenericAddress();

    /**
     * Model tests for GenericAddress
     */
    @Test
    public void testGenericAddress() {
        // TODO: test GenericAddress
    }

    /**
     * Test the property 'flatNumber'
     */
    @Test
    public void flatNumberTest() {
        // TODO: test flatNumber
    }

    /**
     * Test the property 'buildingNumber'
     */
    @Test
    public void buildingNumberTest() {
        // TODO: test buildingNumber
    }

    /**
     * Test the property 'buildingName'
     */
    @Test
    public void buildingNameTest() {
        // TODO: test buildingName
    }

    /**
     * Test the property 'street'
     */
    @Test
    public void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'subStreet'
     */
    @Test
    public void subStreetTest() {
        // TODO: test subStreet
    }

    /**
     * Test the property 'town'
     */
    @Test
    public void townTest() {
        // TODO: test town
    }

    /**
     * Test the property 'postcode'
     */
    @Test
    public void postcodeTest() {
        // TODO: test postcode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

}
