/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.models.LiveVideo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LiveVideosList
 */
public class LiveVideosListTest {
    private final LiveVideosList model = new LiveVideosList();

    /**
     * Model tests for LiveVideosList
     */
    @Test
    public void testLiveVideosList() {
        // TODO: test LiveVideosList
    }

    /**
     * Test the property 'liveVideos'
     */
    @Test
    public void liveVideosTest() {
        // TODO: test liveVideos
    }

}
