/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.models.LivePhoto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LivePhotosList
 */
public class LivePhotosListTest {
    private final LivePhotosList model = new LivePhotosList();

    /**
     * Model tests for LivePhotosList
     */
    @Test
    public void testLivePhotosList() {
        // TODO: test LivePhotosList
    }

    /**
     * Test the property 'livePhotos'
     */
    @Test
    public void livePhotosTest() {
        // TODO: test livePhotos
    }

}
