/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.models.ReportType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ReportTypeGroup
 */
public class ReportTypeGroupTest {
    private final ReportTypeGroup model = new ReportTypeGroup();

    /**
     * Model tests for ReportTypeGroup
     */
    @Test
    public void testReportTypeGroup() {
        // TODO: test ReportTypeGroup
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'groupOnly'
     */
    @Test
    public void groupOnlyTest() {
        // TODO: test groupOnly
    }

    /**
     * Test the property 'reportTypes'
     */
    @Test
    public void reportTypesTest() {
        // TODO: test reportTypes
    }

}
