/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SdkTokenRequest
 */
public class SdkTokenRequestTest {
    private final SdkTokenRequest model = new SdkTokenRequest();

    /**
     * Model tests for SdkTokenRequest
     */
    @Test
    public void testSdkTokenRequest() {
        // TODO: test SdkTokenRequest
    }

    /**
     * Test the property 'applicantId'
     */
    @Test
    public void applicantIdTest() {
        // TODO: test applicantId
    }

    /**
     * Test the property 'referrer'
     */
    @Test
    public void referrerTest() {
        // TODO: test referrer
    }

    /**
     * Test the property 'applicationId'
     */
    @Test
    public void applicationIdTest() {
        // TODO: test applicationId
    }

}
