version: 2
jobs:
  test:
    docker:
      - image: docker.tw.ee/circle_oracle_jvm8:8u181
        user: circleci
    resource_class: small
    environment:
      TERM: vt100
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Install dependencies
          command: bash ./gradlew dependencies testClasses --console=plain
      - run:
          name: Run tests
          command: bash ./gradlew test --info --console=plain
      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/test-results/
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - "~/.gradle"
  release:
    docker:
      - image: docker.tw.ee/circle_oracle_jvm8:8u181
        user: circleci
    resource_class: small
    environment:
      TERM: vt100
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle" }}
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: Set git config
          command: git config --global user.name "TransferWise CircleCI" && git config --global user.email circle@circle.tw.ee
      - run:
          name: Publish release
          command: bash ./gradlew release -Prelease.useAutomaticVersion=true --console=plain

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - release:
          context: artifactory-deploy
          requires:
            - test
          filters:
            branches:
              only: /branch-tw.*/

