/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.onfido.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.onfido.models.Address;
import com.onfido.models.IdNumber;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Applicant
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-05T13:51:13.392Z")
public class Applicant   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("delete_at")
  private OffsetDateTime deleteAt = null;

  @SerializedName("href")
  private String href = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("first_name")
  private String firstName = null;

  @SerializedName("middle_name")
  private String middleName = null;

  @SerializedName("last_name")
  private String lastName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("gender")
  private String gender = null;

  @SerializedName("dob")
  private LocalDate dob = null;

  @SerializedName("telephone")
  private String telephone = null;

  @SerializedName("mobile")
  private String mobile = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("sandbox")
  private Boolean sandbox = null;

  @SerializedName("nationality")
  private String nationality = null;

  @SerializedName("mothers_maiden_name")
  private String mothersMaidenName = null;

  @SerializedName("country_of_birth")
  private String countryOfBirth = null;

  @SerializedName("town_of_birth")
  private String townOfBirth = null;

  @SerializedName("previous_last_name")
  private String previousLastName = null;

  @SerializedName("addresses")
  private List<Address> addresses = new ArrayList<Address>();

  @SerializedName("id_numbers")
  private List<IdNumber> idNumbers = new ArrayList<IdNumber>();

   /**
   * The unique identifier for the applicant
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "The unique identifier for the applicant")
  public String getId() {
    return id;
  }

  public Applicant createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date and time when this applicant was created
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "The date and time when this applicant was created")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Applicant deleteAt(OffsetDateTime deleteAt) {
    this.deleteAt = deleteAt;
    return this;
  }

   /**
   * The date and time when this applicant is scheduled to be deleted, or null if the applicant is not scheduled to be deleted
   * @return deleteAt
  **/
  @ApiModelProperty(example = "null", value = "The date and time when this applicant is scheduled to be deleted, or null if the applicant is not scheduled to be deleted")
  public OffsetDateTime getDeleteAt() {
    return deleteAt;
  }

  public void setDeleteAt(OffsetDateTime deleteAt) {
    this.deleteAt = deleteAt;
  }

  public Applicant href(String href) {
    this.href = href;
    return this;
  }

   /**
   * The uri of this resource
   * @return href
  **/
  @ApiModelProperty(example = "null", value = "The uri of this resource")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public Applicant title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The applicant’s title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Applicant firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * The applicant’s first name
   * @return firstName
  **/
  @ApiModelProperty(example = "null", required = true, value = "The applicant’s first name")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Applicant middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * The applicant’s middle name(s) or initial
   * @return middleName
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s middle name(s) or initial")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public Applicant lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The applicant’s surname
   * @return lastName
  **/
  @ApiModelProperty(example = "null", required = true, value = "The applicant’s surname")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Applicant email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The applicant’s email address
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s email address")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Applicant gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * The applicant’s gender. Valid values are male and female
   * @return gender
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s gender. Valid values are male and female")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public Applicant dob(LocalDate dob) {
    this.dob = dob;
    return this;
  }

   /**
   * The applicant’s date of birth
   * @return dob
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s date of birth")
  public LocalDate getDob() {
    return dob;
  }

  public void setDob(LocalDate dob) {
    this.dob = dob;
  }

  public Applicant telephone(String telephone) {
    this.telephone = telephone;
    return this;
  }

   /**
   * The applicant’s landline phone number
   * @return telephone
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s landline phone number")
  public String getTelephone() {
    return telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  public Applicant mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

   /**
   * The applicant’s mobile phone number
   * @return mobile
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s mobile phone number")
  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public Applicant country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The country where this applicant will be checked. This must be a three-letter ISO code e.g. GBR or USA
   * @return country
  **/
  @ApiModelProperty(example = "null", value = "The country where this applicant will be checked. This must be a three-letter ISO code e.g. GBR or USA")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public Applicant sandbox(Boolean sandbox) {
    this.sandbox = sandbox;
    return this;
  }

   /**
   * Get sandbox
   * @return sandbox
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSandbox() {
    return sandbox;
  }

  public void setSandbox(Boolean sandbox) {
    this.sandbox = sandbox;
  }

  public Applicant nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * The applicant's nationality. This must be a three-letter ISO code e.g. GBR or USA
   * @return nationality
  **/
  @ApiModelProperty(example = "null", value = "The applicant's nationality. This must be a three-letter ISO code e.g. GBR or USA")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public Applicant mothersMaidenName(String mothersMaidenName) {
    this.mothersMaidenName = mothersMaidenName;
    return this;
  }

   /**
   * The applicant’s mothers maiden name
   * @return mothersMaidenName
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s mothers maiden name")
  public String getMothersMaidenName() {
    return mothersMaidenName;
  }

  public void setMothersMaidenName(String mothersMaidenName) {
    this.mothersMaidenName = mothersMaidenName;
  }

  public Applicant countryOfBirth(String countryOfBirth) {
    this.countryOfBirth = countryOfBirth;
    return this;
  }

   /**
   * The applicant’s country of birth
   * @return countryOfBirth
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s country of birth")
  public String getCountryOfBirth() {
    return countryOfBirth;
  }

  public void setCountryOfBirth(String countryOfBirth) {
    this.countryOfBirth = countryOfBirth;
  }

  public Applicant townOfBirth(String townOfBirth) {
    this.townOfBirth = townOfBirth;
    return this;
  }

   /**
   * The applicant’s town of birth
   * @return townOfBirth
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s town of birth")
  public String getTownOfBirth() {
    return townOfBirth;
  }

  public void setTownOfBirth(String townOfBirth) {
    this.townOfBirth = townOfBirth;
  }

  public Applicant previousLastName(String previousLastName) {
    this.previousLastName = previousLastName;
    return this;
  }

   /**
   * The applicant’s previous last name
   * @return previousLastName
  **/
  @ApiModelProperty(example = "null", value = "The applicant’s previous last name")
  public String getPreviousLastName() {
    return previousLastName;
  }

  public void setPreviousLastName(String previousLastName) {
    this.previousLastName = previousLastName;
  }

  public Applicant addresses(List<Address> addresses) {
    this.addresses = addresses;
    return this;
  }

  public Applicant addAddressesItem(Address addressesItem) {
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * Get addresses
   * @return addresses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Address> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<Address> addresses) {
    this.addresses = addresses;
  }

  public Applicant idNumbers(List<IdNumber> idNumbers) {
    this.idNumbers = idNumbers;
    return this;
  }

  public Applicant addIdNumbersItem(IdNumber idNumbersItem) {
    this.idNumbers.add(idNumbersItem);
    return this;
  }

   /**
   * Get idNumbers
   * @return idNumbers
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<IdNumber> getIdNumbers() {
    return idNumbers;
  }

  public void setIdNumbers(List<IdNumber> idNumbers) {
    this.idNumbers = idNumbers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Applicant applicant = (Applicant) o;
    return Objects.equals(this.id, applicant.id) &&
        Objects.equals(this.createdAt, applicant.createdAt) &&
        Objects.equals(this.deleteAt, applicant.deleteAt) &&
        Objects.equals(this.href, applicant.href) &&
        Objects.equals(this.title, applicant.title) &&
        Objects.equals(this.firstName, applicant.firstName) &&
        Objects.equals(this.middleName, applicant.middleName) &&
        Objects.equals(this.lastName, applicant.lastName) &&
        Objects.equals(this.email, applicant.email) &&
        Objects.equals(this.gender, applicant.gender) &&
        Objects.equals(this.dob, applicant.dob) &&
        Objects.equals(this.telephone, applicant.telephone) &&
        Objects.equals(this.mobile, applicant.mobile) &&
        Objects.equals(this.country, applicant.country) &&
        Objects.equals(this.sandbox, applicant.sandbox) &&
        Objects.equals(this.nationality, applicant.nationality) &&
        Objects.equals(this.mothersMaidenName, applicant.mothersMaidenName) &&
        Objects.equals(this.countryOfBirth, applicant.countryOfBirth) &&
        Objects.equals(this.townOfBirth, applicant.townOfBirth) &&
        Objects.equals(this.previousLastName, applicant.previousLastName) &&
        Objects.equals(this.addresses, applicant.addresses) &&
        Objects.equals(this.idNumbers, applicant.idNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, deleteAt, href, title, firstName, middleName, lastName, email, gender, dob, telephone, mobile, country, sandbox, nationality, mothersMaidenName, countryOfBirth, townOfBirth, previousLastName, addresses, idNumbers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Applicant {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deleteAt: ").append(toIndentedString(deleteAt)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    dob: ").append(toIndentedString(dob)).append("\n");
    sb.append("    telephone: ").append(toIndentedString(telephone)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    sandbox: ").append(toIndentedString(sandbox)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    mothersMaidenName: ").append(toIndentedString(mothersMaidenName)).append("\n");
    sb.append("    countryOfBirth: ").append(toIndentedString(countryOfBirth)).append("\n");
    sb.append("    townOfBirth: ").append(toIndentedString(townOfBirth)).append("\n");
    sb.append("    previousLastName: ").append(toIndentedString(previousLastName)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    idNumbers: ").append(toIndentedString(idNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

