/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.onfido.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.onfido.models.Report;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * CheckCreationRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T08:37:28.149Z")
public class CheckCreationRequest   {
  @SerializedName("type")
  private String type = null;

  @SerializedName("redirect_uri")
  private String redirectUri = null;

  @SerializedName("reports")
  private List<Report> reports = new ArrayList<Report>();

  @SerializedName("report_type_groups")
  private List<String> reportTypeGroups = new ArrayList<String>();

  @SerializedName("criminal_history_report_details")
  private Object criminalHistoryReportDetails = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("suppress_form_emails")
  private Boolean suppressFormEmails = null;

  @SerializedName("charge_applicant_for_check")
  private Boolean chargeApplicantForCheck = null;

  @SerializedName("brand_id")
  private String brandId = null;

  @SerializedName("async")
  private Boolean async = null;

  public CheckCreationRequest type(String type) {
    this.type = type;
    return this;
  }

   /**
   * standard or express
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "standard or express")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CheckCreationRequest redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * For standard checks, redirect to this URI when the applicant has submitted their data.
   * @return redirectUri
  **/
  @ApiModelProperty(example = "null", value = "For standard checks, redirect to this URI when the applicant has submitted their data.")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public CheckCreationRequest reports(List<Report> reports) {
    this.reports = reports;
    return this;
  }

  public CheckCreationRequest addReportsItem(Report reportsItem) {
    this.reports.add(reportsItem);
    return this;
  }

   /**
   * Array of Reports being requested for this check.
   * @return reports
  **/
  @ApiModelProperty(example = "null", value = "Array of Reports being requested for this check.")
  public List<Report> getReports() {
    return reports;
  }

  public void setReports(List<Report> reports) {
    this.reports = reports;
  }

  public CheckCreationRequest reportTypeGroups(List<String> reportTypeGroups) {
    this.reportTypeGroups = reportTypeGroups;
    return this;
  }

  public CheckCreationRequest addReportTypeGroupsItem(String reportTypeGroupsItem) {
    this.reportTypeGroups.add(reportTypeGroupsItem);
    return this;
  }

   /**
   * Array containing ids of the Report type groups being requested for.
   * @return reportTypeGroups
  **/
  @ApiModelProperty(example = "null", value = "Array containing ids of the Report type groups being requested for.")
  public List<String> getReportTypeGroups() {
    return reportTypeGroups;
  }

  public void setReportTypeGroups(List<String> reportTypeGroups) {
    this.reportTypeGroups = reportTypeGroups;
  }

  public CheckCreationRequest criminalHistoryReportDetails(Object criminalHistoryReportDetails) {
    this.criminalHistoryReportDetails = criminalHistoryReportDetails;
    return this;
  }

   /**
   * Hash containing properties required for standard or enhanced UK criminal history reports. Only required for checks containing these specific reports. See Criminal history report details arguments.
   * @return criminalHistoryReportDetails
  **/
  @ApiModelProperty(example = "null", value = "Hash containing properties required for standard or enhanced UK criminal history reports. Only required for checks containing these specific reports. See Criminal history report details arguments.")
  public Object getCriminalHistoryReportDetails() {
    return criminalHistoryReportDetails;
  }

  public void setCriminalHistoryReportDetails(Object criminalHistoryReportDetails) {
    this.criminalHistoryReportDetails = criminalHistoryReportDetails;
  }

  public CheckCreationRequest tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public CheckCreationRequest addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Array of tags being assigned to this check.
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "Array of tags being assigned to this check.")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public CheckCreationRequest suppressFormEmails(Boolean suppressFormEmails) {
    this.suppressFormEmails = suppressFormEmails;
    return this;
  }

   /**
   * For standard checks, applicant form will not be automatically sent if this is set to true. You can manually send the form at any time after the check has been created, using the link found in the form_uri attribute of the check object. Defaults to false (i.e., form will be sent automatically by default).
   * @return suppressFormEmails
  **/
  @ApiModelProperty(example = "null", value = "For standard checks, applicant form will not be automatically sent if this is set to true. You can manually send the form at any time after the check has been created, using the link found in the form_uri attribute of the check object. Defaults to false (i.e., form will be sent automatically by default).")
  public Boolean getSuppressFormEmails() {
    return suppressFormEmails;
  }

  public void setSuppressFormEmails(Boolean suppressFormEmails) {
    this.suppressFormEmails = suppressFormEmails;
  }

  public CheckCreationRequest chargeApplicantForCheck(Boolean chargeApplicantForCheck) {
    this.chargeApplicantForCheck = chargeApplicantForCheck;
    return this;
  }

   /**
   * For standard checks, applicants will be presented with a mandatory payment screen before they can submit the applicant form, if this is set to true. In this case, your account will not be charged. Defaults to false.
   * @return chargeApplicantForCheck
  **/
  @ApiModelProperty(example = "null", value = "For standard checks, applicants will be presented with a mandatory payment screen before they can submit the applicant form, if this is set to true. In this case, your account will not be charged. Defaults to false.")
  public Boolean getChargeApplicantForCheck() {
    return chargeApplicantForCheck;
  }

  public void setChargeApplicantForCheck(Boolean chargeApplicantForCheck) {
    this.chargeApplicantForCheck = chargeApplicantForCheck;
  }

  public CheckCreationRequest brandId(String brandId) {
    this.brandId = brandId;
    return this;
  }

   /**
   * ID of the brand under which the check should be conducted. Optional.
   * @return brandId
  **/
  @ApiModelProperty(example = "null", value = "ID of the brand under which the check should be conducted. Optional.")
  public String getBrandId() {
    return brandId;
  }

  public void setBrandId(String brandId) {
    this.brandId = brandId;
  }

  public CheckCreationRequest async(Boolean async) {
    this.async = async;
    return this;
  }

   /**
   * If this is set to true, checks will be queued for processing and no reports will be returned immediately. Defaults to false
   * @return async
  **/
  @ApiModelProperty(example = "null", value = "If this is set to true, checks will be queued for processing and no reports will be returned immediately. Defaults to false")
  public Boolean getAsync() {
    return async;
  }

  public void setAsync(Boolean async) {
    this.async = async;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckCreationRequest checkCreationRequest = (CheckCreationRequest) o;
    return Objects.equals(this.type, checkCreationRequest.type) &&
        Objects.equals(this.redirectUri, checkCreationRequest.redirectUri) &&
        Objects.equals(this.reports, checkCreationRequest.reports) &&
        Objects.equals(this.reportTypeGroups, checkCreationRequest.reportTypeGroups) &&
        Objects.equals(this.criminalHistoryReportDetails, checkCreationRequest.criminalHistoryReportDetails) &&
        Objects.equals(this.tags, checkCreationRequest.tags) &&
        Objects.equals(this.suppressFormEmails, checkCreationRequest.suppressFormEmails) &&
        Objects.equals(this.chargeApplicantForCheck, checkCreationRequest.chargeApplicantForCheck) &&
        Objects.equals(this.brandId, checkCreationRequest.brandId) &&
        Objects.equals(this.async, checkCreationRequest.async);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, redirectUri, reports, reportTypeGroups, criminalHistoryReportDetails, tags, suppressFormEmails, chargeApplicantForCheck, brandId, async);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckCreationRequest {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    reports: ").append(toIndentedString(reports)).append("\n");
    sb.append("    reportTypeGroups: ").append(toIndentedString(reportTypeGroups)).append("\n");
    sb.append("    criminalHistoryReportDetails: ").append(toIndentedString(criminalHistoryReportDetails)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    suppressFormEmails: ").append(toIndentedString(suppressFormEmails)).append("\n");
    sb.append("    chargeApplicantForCheck: ").append(toIndentedString(chargeApplicantForCheck)).append("\n");
    sb.append("    brandId: ").append(toIndentedString(brandId)).append("\n");
    sb.append("    async: ").append(toIndentedString(async)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

