/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.onfido.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * Check
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-14T11:19:36.236Z")
public class Check   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("href")
  private String href = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("tags")
  private List<String> tags = new ArrayList<String>();

  @SerializedName("result")
  private String result = null;

  @SerializedName("download_uri")
  private String downloadUri = null;

  @SerializedName("form_uri")
  private String formUri = null;

  @SerializedName("redirect_uri")
  private String redirectUri = null;

  @SerializedName("results_uri")
  private String resultsUri = null;

  @SerializedName("reports")
  private List<Object> reports = new ArrayList<Object>();

  public Check id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Check createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date and time when this check was created.
   * @return createdAt
  **/
  @ApiModelProperty(example = "null", value = "The date and time when this check was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Check href(String href) {
    this.href = href;
    return this;
  }

   /**
   * The uri of this resource.
   * @return href
  **/
  @ApiModelProperty(example = "null", value = "The uri of this resource.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public Check type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the check: standard or express.
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "The type of the check: standard or express.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Check status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The current state of the check in the checking process.
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "The current state of the check in the checking process.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Check tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Check addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * A list of tags associated with this check.
   * @return tags
  **/
  @ApiModelProperty(example = "null", value = "A list of tags associated with this check.")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public Check result(String result) {
    this.result = result;
    return this;
  }

   /**
   * The overall result of the check, based on the results of the constituent reports.
   * @return result
  **/
  @ApiModelProperty(example = "null", value = "The overall result of the check, based on the results of the constituent reports.")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public Check downloadUri(String downloadUri) {
    this.downloadUri = downloadUri;
    return this;
  }

   /**
   * Get downloadUri
   * @return downloadUri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDownloadUri() {
    return downloadUri;
  }

  public void setDownloadUri(String downloadUri) {
    this.downloadUri = downloadUri;
  }

  public Check formUri(String formUri) {
    this.formUri = formUri;
    return this;
  }

   /**
   * Get formUri
   * @return formUri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFormUri() {
    return formUri;
  }

  public void setFormUri(String formUri) {
    this.formUri = formUri;
  }

  public Check redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * Get redirectUri
   * @return redirectUri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }

  public Check resultsUri(String resultsUri) {
    this.resultsUri = resultsUri;
    return this;
  }

   /**
   * Get resultsUri
   * @return resultsUri
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResultsUri() {
    return resultsUri;
  }

  public void setResultsUri(String resultsUri) {
    this.resultsUri = resultsUri;
  }

  public Check reports(List<Object> reports) {
    this.reports = reports;
    return this;
  }

  public Check addReportsItem(Object reportsItem) {
    this.reports.add(reportsItem);
    return this;
  }

   /**
   * Get reports
   * @return reports
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Object> getReports() {
    return reports;
  }

  public void setReports(List<Object> reports) {
    this.reports = reports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Check check = (Check) o;
    return Objects.equals(this.id, check.id) &&
        Objects.equals(this.createdAt, check.createdAt) &&
        Objects.equals(this.href, check.href) &&
        Objects.equals(this.type, check.type) &&
        Objects.equals(this.status, check.status) &&
        Objects.equals(this.tags, check.tags) &&
        Objects.equals(this.result, check.result) &&
        Objects.equals(this.downloadUri, check.downloadUri) &&
        Objects.equals(this.formUri, check.formUri) &&
        Objects.equals(this.redirectUri, check.redirectUri) &&
        Objects.equals(this.resultsUri, check.resultsUri) &&
        Objects.equals(this.reports, check.reports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, href, type, status, tags, result, downloadUri, formUri, redirectUri, resultsUri, reports);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Check {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    downloadUri: ").append(toIndentedString(downloadUri)).append("\n");
    sb.append("    formUri: ").append(toIndentedString(formUri)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    resultsUri: ").append(toIndentedString(resultsUri)).append("\n");
    sb.append("    reports: ").append(toIndentedString(reports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

