/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.onfido.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * GenericAddress
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-16T08:37:28.149Z")
public class GenericAddress   {
  @SerializedName("flat_number")
  private String flatNumber = null;

  @SerializedName("building_number")
  private String buildingNumber = null;

  @SerializedName("building_name")
  private String buildingName = null;

  @SerializedName("street")
  private String street = null;

  @SerializedName("sub_street")
  private String subStreet = null;

  @SerializedName("town")
  private String town = null;

  @SerializedName("postcode")
  private String postcode = null;

  @SerializedName("country")
  private String country = null;

  public GenericAddress flatNumber(String flatNumber) {
    this.flatNumber = flatNumber;
    return this;
  }

   /**
   * The flat number of this address
   * @return flatNumber
  **/
  @ApiModelProperty(example = "null", value = "The flat number of this address")
  public String getFlatNumber() {
    return flatNumber;
  }

  public void setFlatNumber(String flatNumber) {
    this.flatNumber = flatNumber;
  }

  public GenericAddress buildingNumber(String buildingNumber) {
    this.buildingNumber = buildingNumber;
    return this;
  }

   /**
   * The building number of this address
   * @return buildingNumber
  **/
  @ApiModelProperty(example = "null", value = "The building number of this address")
  public String getBuildingNumber() {
    return buildingNumber;
  }

  public void setBuildingNumber(String buildingNumber) {
    this.buildingNumber = buildingNumber;
  }

  public GenericAddress buildingName(String buildingName) {
    this.buildingName = buildingName;
    return this;
  }

   /**
   * The building name of this address
   * @return buildingName
  **/
  @ApiModelProperty(example = "null", value = "The building name of this address")
  public String getBuildingName() {
    return buildingName;
  }

  public void setBuildingName(String buildingName) {
    this.buildingName = buildingName;
  }

  public GenericAddress street(String street) {
    this.street = street;
    return this;
  }

   /**
   * The street of the applicant’s address
   * @return street
  **/
  @ApiModelProperty(example = "null", value = "The street of the applicant’s address")
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public GenericAddress subStreet(String subStreet) {
    this.subStreet = subStreet;
    return this;
  }

   /**
   * The sub-street of the applicant’s address
   * @return subStreet
  **/
  @ApiModelProperty(example = "null", value = "The sub-street of the applicant’s address")
  public String getSubStreet() {
    return subStreet;
  }

  public void setSubStreet(String subStreet) {
    this.subStreet = subStreet;
  }

  public GenericAddress town(String town) {
    this.town = town;
    return this;
  }

   /**
   * The town of the applicant’s address
   * @return town
  **/
  @ApiModelProperty(example = "null", value = "The town of the applicant’s address")
  public String getTown() {
    return town;
  }

  public void setTown(String town) {
    this.town = town;
  }

  public GenericAddress postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * The postcode or ZIP of the applicant’s address
   * @return postcode
  **/
  @ApiModelProperty(example = "null", value = "The postcode or ZIP of the applicant’s address")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public GenericAddress country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The 3 character ISO country code of this address. For example, GBR is the country code for the United Kingdom
   * @return country
  **/
  @ApiModelProperty(example = "null", value = "The 3 character ISO country code of this address. For example, GBR is the country code for the United Kingdom")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericAddress genericAddress = (GenericAddress) o;
    return Objects.equals(this.flatNumber, genericAddress.flatNumber) &&
        Objects.equals(this.buildingNumber, genericAddress.buildingNumber) &&
        Objects.equals(this.buildingName, genericAddress.buildingName) &&
        Objects.equals(this.street, genericAddress.street) &&
        Objects.equals(this.subStreet, genericAddress.subStreet) &&
        Objects.equals(this.town, genericAddress.town) &&
        Objects.equals(this.postcode, genericAddress.postcode) &&
        Objects.equals(this.country, genericAddress.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flatNumber, buildingNumber, buildingName, street, subStreet, town, postcode, country);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericAddress {\n");
    
    sb.append("    flatNumber: ").append(toIndentedString(flatNumber)).append("\n");
    sb.append("    buildingNumber: ").append(toIndentedString(buildingNumber)).append("\n");
    sb.append("    buildingName: ").append(toIndentedString(buildingName)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    subStreet: ").append(toIndentedString(subStreet)).append("\n");
    sb.append("    town: ").append(toIndentedString(town)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

