/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.onfido.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.onfido.models.LivePhoto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * LivePhotosList
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-27T17:09:58.121Z")
public class LivePhotosList   {
  @SerializedName("live_photos")
  private List<LivePhoto> livePhotos = new ArrayList<LivePhoto>();

  public LivePhotosList livePhotos(List<LivePhoto> livePhotos) {
    this.livePhotos = livePhotos;
    return this;
  }

  public LivePhotosList addLivePhotosItem(LivePhoto livePhotosItem) {
    this.livePhotos.add(livePhotosItem);
    return this;
  }

   /**
   * Get livePhotos
   * @return livePhotos
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LivePhoto> getLivePhotos() {
    return livePhotos;
  }

  public void setLivePhotos(List<LivePhoto> livePhotos) {
    this.livePhotos = livePhotos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LivePhotosList livePhotosList = (LivePhotosList) o;
    return Objects.equals(this.livePhotos, livePhotosList.livePhotos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(livePhotos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LivePhotosList {\n");
    
    sb.append("    livePhotos: ").append(toIndentedString(livePhotos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

