/*
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.models.LiveVideo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LiveVideosList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-04-25T11:17:56.186Z[GMT]")
public class LiveVideosList {
  public static final String SERIALIZED_NAME_LIVE_VIDEOS = "live_videos";
  @SerializedName(SERIALIZED_NAME_LIVE_VIDEOS)
  private List<LiveVideo> liveVideos = new ArrayList<>();

  public LiveVideosList liveVideos(List<LiveVideo> liveVideos) {
    this.liveVideos = liveVideos;
    return this;
  }

  public LiveVideosList addLiveVideosItem(LiveVideo liveVideosItem) {
    if (this.liveVideos == null) {
      this.liveVideos = new ArrayList<>();
    }
    this.liveVideos.add(liveVideosItem);
    return this;
  }

   /**
   * Get liveVideos
   * @return liveVideos
  **/
  @ApiModelProperty(value = "")
  public List<LiveVideo> getLiveVideos() {
    return liveVideos;
  }

  public void setLiveVideos(List<LiveVideo> liveVideos) {
    this.liveVideos = liveVideos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveVideosList liveVideosList = (LiveVideosList) o;
    return Objects.equals(this.liveVideos, liveVideosList.liveVideos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(liveVideos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveVideosList {\n");
    sb.append("    liveVideos: ").append(toIndentedString(liveVideos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

