/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.onfido.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.onfido.models.LiveVideo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * LiveVideosList
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-05T13:51:13.392Z")
public class LiveVideosList   {
  @SerializedName("live_videos")
  private List<LiveVideo> liveVideos = new ArrayList<LiveVideo>();

  public LiveVideosList liveVideos(List<LiveVideo> liveVideos) {
    this.liveVideos = liveVideos;
    return this;
  }

  public LiveVideosList addLiveVideosItem(LiveVideo liveVideosItem) {
    this.liveVideos.add(liveVideosItem);
    return this;
  }

   /**
   * Get liveVideos
   * @return liveVideos
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<LiveVideo> getLiveVideos() {
    return liveVideos;
  }

  public void setLiveVideos(List<LiveVideo> liveVideos) {
    this.liveVideos = liveVideos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LiveVideosList liveVideosList = (LiveVideosList) o;
    return Objects.equals(this.liveVideos, liveVideosList.liveVideos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(liveVideos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LiveVideosList {\n");
    
    sb.append("    liveVideos: ").append(toIndentedString(liveVideos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

