/**
 * Onfido API
 * The Onfido API is used to submit check requests.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.onfido.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.onfido.models.ReportTypeGroup;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ReportTypeGroupsList
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-08T15:56:57.777Z")
public class ReportTypeGroupsList   {
  @SerializedName("report_type_groups")
  private List<ReportTypeGroup> reportTypeGroups = new ArrayList<ReportTypeGroup>();

  public ReportTypeGroupsList reportTypeGroups(List<ReportTypeGroup> reportTypeGroups) {
    this.reportTypeGroups = reportTypeGroups;
    return this;
  }

  public ReportTypeGroupsList addReportTypeGroupsItem(ReportTypeGroup reportTypeGroupsItem) {
    this.reportTypeGroups.add(reportTypeGroupsItem);
    return this;
  }

   /**
   * Get reportTypeGroups
   * @return reportTypeGroups
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ReportTypeGroup> getReportTypeGroups() {
    return reportTypeGroups;
  }

  public void setReportTypeGroups(List<ReportTypeGroup> reportTypeGroups) {
    this.reportTypeGroups = reportTypeGroups;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportTypeGroupsList reportTypeGroupsList = (ReportTypeGroupsList) o;
    return Objects.equals(this.reportTypeGroups, reportTypeGroupsList.reportTypeGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportTypeGroups);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportTypeGroupsList {\n");
    
    sb.append("    reportTypeGroups: ").append(toIndentedString(reportTypeGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

